// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aisp.Common.DAL;

#nullable disable

namespace aisp.Common.DAL.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20260903033606_AddNpcNamePlate")]
    partial class AddNpcNamePlate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("aisp.Common.DAL.Entities.AdventureListing", b =>
                {
                    b.Property<long>("ScriptId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(768)
                        .HasColumnType("TEXT");

                    b.Property<long>("ContentSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ContentsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DelistedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Genre")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ListedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Official")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalesCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScriptId");

                    b.HasIndex("State", "Genre");

                    b.HasIndex("UserId", "WorkId");

                    b.ToTable("AdventureListings", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.AdventureListingContent", b =>
                {
                    b.Property<long>("ScriptId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Datalist")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Script")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("ScriptId");

                    b.ToTable("AdventureListingContents", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.AdventurePurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuthorShare")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyerCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HiddenFromDownloads")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HiddenFromHistory")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchasedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("ScriptId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScriptId");

                    b.HasIndex("SettledAt");

                    b.HasIndex("BuyerUserId", "ScriptId");

                    b.ToTable("AdventurePurchases", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.AdventureTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Purpose")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ScriptId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("AdventureTickets", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.AdventureWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Sheets")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Uploaded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WorkId")
                        .IsUnique();

                    b.ToTable("AdventureWorks", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<uint>("BloodType")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CharadollPersonality")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)2);

                    b.Property<int?>("CircleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("CurrentMapId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("FaceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Hairstyle")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HomeIslandId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoggedInAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Like1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Like2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Like3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LikeDesc1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LikeDesc2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LikeDesc3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("UserStatusIconId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0u);

                    b.Property<string>("UserStatusText")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(49)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.HasIndex("CurrentRoomId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.CharacterEquipment", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "SlotIndex");

                    b.HasIndex("ItemId");

                    b.ToTable("CharacterEquipment", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.CharacterEventStatus", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "EventKey");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterEventStatuses", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.CharacterInventory", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("CharacterId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("CharacterInventory", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("BalloonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CircleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("DistId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Rejected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CharacterId", "CreatedAt");

                    b.HasIndex("CircleId", "CreatedAt");

                    b.HasIndex("Kind", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("MapId", "ChannelId", "CreatedAt");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Circle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("LeaderCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(37)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<uint>("MarkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(751)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("MessageDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(46)
                        .HasColumnType("TEXT");

                    b.Property<uint>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("LeaderCharacterId");

                    b.HasIndex("Name");

                    b.ToTable("Circles", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.CircleJoinRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CircleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("RequesterCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetCharacterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RequesterCharacterId", "Status");

                    b.HasIndex("TargetCharacterId", "Status");

                    b.HasIndex("CircleId", "TargetCharacterId", "Status");

                    b.ToTable("CircleJoinRequests", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.CircleMember", b =>
                {
                    b.Property<int>("CircleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AuthLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CircleId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CircleMembers", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.FriendRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("RequesterCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetCharacterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RequesterCharacterId", "Status");

                    b.HasIndex("TargetCharacterId", "Status");

                    b.ToTable("FriendRequests", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Friendship", b =>
                {
                    b.Property<int>("CharacterIdLow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterIdHigh")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CharacterIdLow", "CharacterIdHigh");

                    b.HasIndex("CharacterIdHigh");

                    b.ToTable("Friendships", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Furniture", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PlacementFlags")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("Furniture", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.GameChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelNum")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("CurrentUsers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<uint>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10990100u);

                    b.Property<uint>("MaxUsers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1000u);

                    b.Property<ushort>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Channels", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CatalogCategory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IconId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Socket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.LocalisedText", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Language")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key", "Language");

                    b.HasIndex("Key");

                    b.ToTable("LocalisedTexts", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Map", b =>
                {
                    b.Property<long>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Island")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SpawnRotation")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SpawnX")
                        .HasColumnType("REAL");

                    b.Property<float>("SpawnY")
                        .HasColumnType("REAL");

                    b.Property<float>("SpawnZ")
                        .HasColumnType("REAL");

                    b.HasKey("MapId");

                    b.ToTable("Maps", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.MapLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Behavior")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Depth")
                        .HasColumnType("REAL");

                    b.Property<string>("DestinationMapIds")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DestinationSpawnRotation")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("DestinationSpawnX")
                        .HasColumnType("REAL");

                    b.Property<float?>("DestinationSpawnY")
                        .HasColumnType("REAL");

                    b.Property<float?>("DestinationSpawnZ")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Length")
                        .HasColumnType("REAL");

                    b.Property<float>("PositionX")
                        .HasColumnType("REAL");

                    b.Property<float>("PositionY")
                        .HasColumnType("REAL");

                    b.Property<float>("PositionZ")
                        .HasColumnType("REAL");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceMapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Yaw")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceMapId", "ChannelId", "SortOrder");

                    b.ToTable("MapLinks", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.MyRoomFurniture", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("FurnitureId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DirectionX")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DirectionY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("PositionX")
                        .HasColumnType("REAL");

                    b.Property<float>("PositionY")
                        .HasColumnType("REAL");

                    b.Property<float>("PositionZ")
                        .HasColumnType("REAL");

                    b.HasKey("RoomId", "FurnitureId");

                    b.HasIndex("ItemId");

                    b.ToTable("MyRoomFurniture", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Nicotv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("CommentVisibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0u);

                    b.Property<uint>("FurnitureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<uint>("PlaybackState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0u);

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "FurnitureId")
                        .IsUnique();

                    b.ToTable("Nicotvs", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Npc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(-1);

                    b.Property<DateTime>("DateEndUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999));

                    b.Property<DateTime>("DateStartUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc));

                    b.Property<int>("DayPhase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(-1);

                    b.Property<string>("EventKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventKind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("InteractionType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<long>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<uint>("NamePlate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(4u);

                    b.Property<long>("NpcObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rotation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShopId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<float>("X")
                        .HasColumnType("REAL");

                    b.Property<float>("Y")
                        .HasColumnType("REAL");

                    b.Property<float>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("NpcObjectId")
                        .IsUnique();

                    b.HasIndex("ShopId");

                    b.HasIndex("MapId", "SortOrder");

                    b.ToTable("Npcs", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.NpcEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NpcId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NpcId", "SlotIndex")
                        .IsUnique();

                    b.ToTable("NpcEquipment", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.PendingMapTransfer", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<uint>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MyRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rotation")
                        .HasColumnType("INTEGER");

                    b.Property<float>("X")
                        .HasColumnType("REAL");

                    b.Property<float>("Y")
                        .HasColumnType("REAL");

                    b.Property<float>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("UserId");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("PendingMapTransfers", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.ReportTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReporterCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReporterCharacterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReporterUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReporterUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionAction")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("ReportTickets", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.ReportTicketChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Rejected")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReportTicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReportTicketId");

                    b.HasIndex("ReportTicketId", "CreatedAt");

                    b.ToTable("ReportTicketChatMessages", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.ReportTicketPlayer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("ReportTicketId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportTicketId");

                    b.ToTable("ReportTicketPlayers", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Robo", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("RoboId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("AiScriptId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AvailableStatusPoints")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("BirthDay")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("BirthMonth")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("BloodType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<ulong>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ExperienceToNextLevel")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Face")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Hairstyle")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Like1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Like2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Like3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("LikeDesc1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("LikeDesc2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("LikeDesc3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<uint>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(37)
                        .HasColumnType("TEXT");

                    b.Property<uint>("NamePlate")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<uint>("ProfileUnknownDword04")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0u);

                    b.Property<uint>("ProfileUnknownDword08")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0u);

                    b.Property<uint>("State")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("StatusPoints")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("UserStatusIconId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserStatusText")
                        .IsRequired()
                        .HasMaxLength(49)
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "RoboId");

                    b.ToTable("Robos", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.RoboBattleAbility", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("RoboId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AbilitySet")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AbilityIndex")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "RoboId", "AbilitySet", "AbilityIndex");

                    b.ToTable("RoboBattleAbilities", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.RoboDistributedStatusPoint", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("RoboId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("StatusIndex")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "RoboId", "StatusIndex");

                    b.ToTable("RoboDistributedStatusPoints", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.RoboEquipment", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("RoboId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Socket")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "RoboId", "SlotIndex");

                    b.ToTable("RoboEquipment", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.RoboItemUseEffect", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("RoboId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("EffectType")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ItemDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ItemSerialId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("OverwriteExisting")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Parameter0")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Parameter1")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Parameter2")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Parameter3")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Parameter4")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "RoboId", "SlotIndex");

                    b.ToTable("RoboItemUseEffects", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.RoboTpsBattleData", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("RoboId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ActionFlags")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ActionProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ActionReferenceX")
                        .HasColumnType("REAL");

                    b.Property<float>("ActionReferenceY")
                        .HasColumnType("REAL");

                    b.Property<float>("ActionVerticalRange")
                        .HasColumnType("REAL");

                    b.Property<uint>("ActiveSkillId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("CollisionRadius")
                        .HasColumnType("REAL");

                    b.Property<ulong>("CosplayExperience")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CosplayExperienceToNextLevel")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("CosplayId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CosplayLevel")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CosplayStatusPoints")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CurrentHearts")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HitPointsBaseMaximum")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HitPointsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HitPointsMaximumBonus")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HitPointsMaximumPenalty")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MaximumHearts")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("StaminaCostReductionBonus")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("StaminaCostReductionPenalty")
                        .HasColumnType("INTEGER");

                    b.Property<float>("StaminaCurrent")
                        .HasColumnType("REAL");

                    b.Property<float>("StaminaRecoveryRate")
                        .HasColumnType("REAL");

                    b.Property<ulong>("StatusEffectFlags")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TankBaseMaximum")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TankCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TankMaximumBonus")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TankMaximumPenalty")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "RoboId");

                    b.ToTable("RoboTpsBattleData", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("My Room");

                    b.Property<int>("OwnerCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Security")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0u);

                    b.Property<byte>("Stage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("OwnerCharacterId", "IsDefault");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.SessionPresence", b =>
                {
                    b.Property<Guid>("ConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rotation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("X")
                        .HasColumnType("REAL");

                    b.Property<float>("Y")
                        .HasColumnType("REAL");

                    b.Property<float>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("ConnectionId");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("ServerType", "CharacterId");

                    b.HasIndex("ServerType", "UserId");

                    b.HasIndex("ServerType", "MapId", "ChannelId");

                    b.ToTable("SessionPresences", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BannerVisualId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Shops", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AiPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NicoPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<int>("ShopId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShopId", "ItemId")
                        .IsUnique();

                    b.HasIndex("ShopId", "SortOrder");

                    b.ToTable("ShopItems", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AdventureSalesBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<int>("AdventureSheetStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<long>("AiPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<string>("BanReason")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BannedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BannedUntil")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("KickedUntil")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Language")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("PreferredLanguage");

                    b.Property<DateTime?>("LastLoggedInAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NextAdventureWorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<long>("NicoPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("PasswordHash");

                    b.Property<byte>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<long>("StorageDeposit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OTP")
                        .IsUnique();

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.UserStorageItem", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("UserId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("UserStorageItems", (string)null);
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.World", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.AdventureListing", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.AdventureListingContent", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.AdventureListing", "Listing")
                        .WithOne("Content")
                        .HasForeignKey("aisp.Common.DAL.Entities.AdventureListingContent", "ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.AdventurePurchase", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.User", "BuyerUser")
                        .WithMany()
                        .HasForeignKey("BuyerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aisp.Common.DAL.Entities.AdventureListing", "Listing")
                        .WithMany()
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyerUser");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.AdventureWork", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Character", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Circle", "Circle")
                        .WithMany()
                        .HasForeignKey("CircleId");

                    b.HasOne("aisp.Common.DAL.Entities.Room", "CurrentRoom")
                        .WithMany()
                        .HasForeignKey("CurrentRoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("aisp.Common.DAL.Entities.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circle");

                    b.Navigation("CurrentRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.CharacterEquipment", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Character", "Character")
                        .WithMany("Equipment")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aisp.Common.DAL.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.CharacterEventStatus", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.CharacterInventory", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Character", "Character")
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aisp.Common.DAL.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Circle", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Character", "LeaderCharacter")
                        .WithMany()
                        .HasForeignKey("LeaderCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeaderCharacter");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.CircleJoinRequest", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Circle", "Circle")
                        .WithMany("JoinRequests")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aisp.Common.DAL.Entities.Character", "RequesterCharacter")
                        .WithMany()
                        .HasForeignKey("RequesterCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("aisp.Common.DAL.Entities.Character", "TargetCharacter")
                        .WithMany()
                        .HasForeignKey("TargetCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circle");

                    b.Navigation("RequesterCharacter");

                    b.Navigation("TargetCharacter");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.CircleMember", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Character", "Character")
                        .WithMany("CircleMemberships")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aisp.Common.DAL.Entities.Circle", "Circle")
                        .WithMany("Members")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Circle");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.FriendRequest", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Character", "RequesterCharacter")
                        .WithMany()
                        .HasForeignKey("RequesterCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("aisp.Common.DAL.Entities.Character", "TargetCharacter")
                        .WithMany()
                        .HasForeignKey("TargetCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequesterCharacter");

                    b.Navigation("TargetCharacter");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Friendship", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Character", "CharacterHigh")
                        .WithMany()
                        .HasForeignKey("CharacterIdHigh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("aisp.Common.DAL.Entities.Character", "CharacterLow")
                        .WithMany()
                        .HasForeignKey("CharacterIdLow")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CharacterHigh");

                    b.Navigation("CharacterLow");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Furniture", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Item", "Item")
                        .WithOne("Furniture")
                        .HasForeignKey("aisp.Common.DAL.Entities.Furniture", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.MyRoomFurniture", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Furniture", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("aisp.Common.DAL.Entities.Room", "Room")
                        .WithMany("Furniture")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Nicotv", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.MyRoomFurniture", "Furniture")
                        .WithOne("Nicotv")
                        .HasForeignKey("aisp.Common.DAL.Entities.Nicotv", "RoomId", "FurnitureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Furniture");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Npc", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Shop", "Shop")
                        .WithMany("Npcs")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.NpcEquipment", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Npc", "Npc")
                        .WithMany("Equipment")
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.ReportTicketChatMessage", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.ReportTicket", "ReportTicket")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ReportTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportTicket");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.ReportTicketPlayer", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.ReportTicket", "ReportTicket")
                        .WithMany("Players")
                        .HasForeignKey("ReportTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportTicket");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Robo", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Character", "Character")
                        .WithMany("Robos")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.RoboBattleAbility", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.RoboTpsBattleData", "TpsBattleData")
                        .WithMany("BattleAbilities")
                        .HasForeignKey("CharacterId", "RoboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TpsBattleData");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.RoboDistributedStatusPoint", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Robo", "Robo")
                        .WithMany("DistributedStatusPoints")
                        .HasForeignKey("CharacterId", "RoboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Robo");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.RoboEquipment", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Robo", "Robo")
                        .WithMany("Equipment")
                        .HasForeignKey("CharacterId", "RoboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Robo");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.RoboItemUseEffect", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Robo", "Robo")
                        .WithMany("ItemUseEffects")
                        .HasForeignKey("CharacterId", "RoboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Robo");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.RoboTpsBattleData", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Robo", "Robo")
                        .WithOne("TpsBattleData")
                        .HasForeignKey("aisp.Common.DAL.Entities.RoboTpsBattleData", "CharacterId", "RoboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Robo");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Room", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Character", "OwnerCharacter")
                        .WithMany("Rooms")
                        .HasForeignKey("OwnerCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerCharacter");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.ShopItem", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Shop", "Shop")
                        .WithMany("Items")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.UserSession", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.UserStorageItem", b =>
                {
                    b.HasOne("aisp.Common.DAL.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("aisp.Common.DAL.Entities.User", "User")
                        .WithMany("StorageItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.AdventureListing", b =>
                {
                    b.Navigation("Content");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Character", b =>
                {
                    b.Navigation("CircleMemberships");

                    b.Navigation("Equipment");

                    b.Navigation("Inventory");

                    b.Navigation("Robos");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Circle", b =>
                {
                    b.Navigation("JoinRequests");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Item", b =>
                {
                    b.Navigation("Furniture");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.MyRoomFurniture", b =>
                {
                    b.Navigation("Nicotv");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Npc", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.ReportTicket", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Robo", b =>
                {
                    b.Navigation("DistributedStatusPoints");

                    b.Navigation("Equipment");

                    b.Navigation("ItemUseEffects");

                    b.Navigation("TpsBattleData")
                        .IsRequired();
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.RoboTpsBattleData", b =>
                {
                    b.Navigation("BattleAbilities");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Room", b =>
                {
                    b.Navigation("Furniture");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.Shop", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Npcs");
                });

            modelBuilder.Entity("aisp.Common.DAL.Entities.User", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Sessions");

                    b.Navigation("StorageItems");
                });
#pragma warning restore 612, 618
        }
    }
}
